sudo: required
language: cpp


env:
  global:
   - MAKEFLAGS="-j 2"

matrix:
  include:

    # 1/ Linux Clang Builds
    - os: linux
      compiler: clang
      addons: &clang38
        apt:
          sources: 
            - llvm-toolchain-trusty-3.8
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-5-dev
            - clang-3.8
            - cmake
            - cmake-data
            #- mono-devel
      env: 
        - COMPILERCXX='clang++-3.8'
        - COMPILERC='clang-3.8'

    - os: linux
      compiler: clang
      addons: &clang39
        apt:
          sources: 
            - llvm-toolchain-trusty-3.9
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-6-dev
            - clang-3.9
            - cmake
            - cmake-data
            #- mono-devel
      env: 
        - COMPILERCXX='clang++-3.9'
        - COMPILERC='clang-3.9'

    - os: linux
      compiler: clang
      addons: &clang40
        apt:
          sources: 
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-6-dev
            - clang-4.0
            - cmake
            - cmake-data
            #- mono-devel
      env: 
        - COMPILERCXX='clang++-4.0'
        - COMPILERC='clang-4.0'
    
    - os: linux
      compiler: clang
      addons: &clang50
        apt:
          sources: 
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-7-dev
            - clang-5.0
            - cmake
            - cmake-data
            #- mono-devel
      env: 
        - COMPILERCXX='clang++-5.0'
        - COMPILERC='clang-5.0'
    
    # 2/ Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc5
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - cmake-data
            #- mono-devel
      env:
        - COMPILERCXX='g++-5'
        - COMPILERC='gcc-5'

    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
            - cmake-data
            #- mono-devel
      env:
        - COMPILERCXX='g++-6'
        - COMPILERC='gcc-6'
        
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - cmake-data
            #- mono-devel
      env:
        - COMPILERCXX='g++-7'
        - COMPILERC='gcc-7'
        
before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo apt install apt-transport-https
  - echo "deb https://download.mono-project.com/repo/ubuntu stable-trusty main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  - sudo apt update
  - sudo apt-get -f install mono-devel
#  - sudo apt-get install mono-devel
  
script:
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_C_COMPILER=$COMPILERC -DCMAKE_CXX_COMPILER=$COMPILERCXX ..
  - cmake --build .
